# Generated by Django 5.0.3 on 2024-05-14 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 6, 29, 34, 768672, tzinfo=datetime.timezone.utc), verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 18, 44, 34, 767698, tzinfo=datetime.timezone.utc)),
        ),
    ]
