# Generated by Django 5.0.3 on 2024-05-09 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actions/'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='winner_shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auctions_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
