# Generated by Django 5.0.3 on 2024-05-13 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_otp_alter_auction_current_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='current_price',
            field=models.IntegerField(verbose_name='current_price'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 14, 3, 48, 5, 629983, tzinfo=datetime.timezone.utc), verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_price',
            field=models.IntegerField(verbose_name='start_price'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='collection',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='us_collect',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 16, 3, 5, 629983, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='typedelivery',
            name='additional_fee_per_500gram',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='typedelivery',
            name='price',
            field=models.IntegerField(),
        ),
    ]
