# Generated by Django 5.0.3 on 2024-05-15 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_is_waiting_accept_alter_auction_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 23, 40, 22, 207821, tzinfo=datetime.timezone.utc), verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='expired_at',
            field=models.DateTimeField(),
        ),
    ]
