# Generated by Django 5.0.3 on 2024-05-09 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_auction_image_alter_auction_winner_shipper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 4, 53, 48, 151267), verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='start_time'),
        ),
    ]
