# Generated by Django 5.0.3 on 2024-05-10 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_auction_end_time_alter_auction_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 1, 38, 31, 862328, tzinfo=datetime.timezone.utc), verbose_name='end_time'),
        ),
    ]
