# Generated by Django 5.0.3 on 2024-05-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_auction_end_time_alter_otp_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='end_time'),
        ),
    ]
