# Generated by Django 5.0.3 on 2024-05-11 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_auction_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 11, 17, 52, 3, 361128, tzinfo=datetime.timezone.utc), verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
